### ISSUE TITLE
Ambiguity between multiple wallet views

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#119] opened 2024-11-28 12:22 UTC
I am sure we're aware of this , but would be good to discuss how we can clean this one up. 

Let me try to recap all the views we have first:

1. `/funds` which you access when you click on the `Send` on the dashboard. 

![Screenshot 2024-11-28 at 12 50 50](https://github.com/user-attachments/assets/7526a29e-b9e4-4d48-ac43-013a556370e8)

2. `settings/wallet/funds` which you access from `Settings> On-chain funds` which  has the functionality 
![Screenshot 2024-11-28 at 13 07 04](https://github.com/user-attachments/assets/78d79006-49db-4070-b30a-3c7748006405)

3. `settings/wallet which is a duplicate of 4. `Settings` > **On-chain wallet** 

![Screenshot 2024-11-28 at 13 18 09](https://github.com/user-attachments/assets/f7e16fce-1451-469b-b952-5bf985206811)

4. `settings/wallet`which you access by Settings > **On-chain funds** clicking `settings icon` in the top right. 

![Screenshot 2024-11-28 at 13 18 09](https://github.com/user-attachments/assets/0b211c64-7f79-44a3-b52b-f05ecc64304b)

I think we overcomplicated stuff here.
1. is send
2. is receive
3. 3 and 4 are duplicates and we should remove onchain wallet setting and call this wallet settings

Just to bring things again into perspective: 

Every wallet has 4 basic views:
- /Wallet - transaction overview with balance send and receive buttons
- Wallet/Send - sending
- Wallet/Receive - receiving 
- Wallet/Settings - for wallet related settings

@dennisreimann I hope outlined this accurently, tbh it was quite tricky as I got lost in the navigation. Do you have any reasoning or ideas how we could tackle this cleanup? Perhaps there are some technical considerations I am missing out here, but I am sure a lot of this is caused by us not knowing  specifically how we want to do this, and perhaps overthinking on the receive functionality.

**Comment by pavlenex** [comment] 2024-11-29 13:07
It seems @dennisreimann pushed some changes that make most of this issue obsolete now.

However, there are still two wallets for some reason:
1. Dashboard > Send which is lightning + onchain (what we want) but it's dependent on wrong API points causing #117 <img width="1250" alt="Screenshot 2024-11-29 at 14 04 38" src="https://github.com/user-attachments/assets/cbdb5f88-480b-4a4d-8172-b9e6341686bd">

2. Settings > On-chain wallet (which seems to be only on-chain wallet) and it works
<img width="724" alt="Screenshot 2024-11-29 at 14 06 38" src="https://github.com/user-attachments/assets/89bceab4-4d9b-4e06-bc18-2ae5d03be7cd">

Ideal solution here is to have a single wallet, that unifies lightning and on-chain, but also works regardless of the server settings, so a combination of both views.

**Comment by dstrukt** [comment] 2024-12-02 19:48
Agree, getting the foundation there was very helpful, but the views need to be unified and cleaned up now that they're working as intended!

**Comment by dstrukt** [comment] 2024-12-02 20:23
Agree with @pavlenex and see a similar proposal:

1. Wallet (either will be part of the Dashboard tab) or it's own tab
- Includes the Unified Balance 
- Lists the latest transactions, possibly invoices
- Send / Receive buttons

2. Wallet/Send - Send view, accessible only through the Wallet

3. Wallet/Receive - Receive view, accessible only through the Wallet, maybe we eventually add Lightning support here, but at the moment, Lightning receive is done through the Keypad

4. Wallet/Settings - for Lightning and On-chain Wallet related Settings

No need for it to be more complicated.

**Closed** 2024-12-09 15:44 UTC
Labels: design
